import { useEffect, useState } from "react";
import ReactMarkdown from "react-markdown";
import { Loader2, Sparkles, RefreshCw } from "lucide-react";
import { useDataset } from "@/lib/data-store";
import { summarizeForAi } from "@/lib/eda";
import { Panel } from "./kpi-card";

export function InsightsPanel() {
  const { rows, profile } = useDataset();
  const [text, setText] = useState("");
  const [loading, setLoading] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const run = async () => {
    if (!profile) return;
    setLoading(true);
    setErr(null);
    try {
      const res = await fetch("/api/insights", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ context: summarizeForAi(profile, rows) }),
      });
      if (!res.ok) throw new Error(await res.text());
      const data = (await res.json()) as { text: string };
      setText(data.text);
    } catch (e) {
      setErr(e instanceof Error ? e.message : "Failed");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (profile && !text) void run();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profile]);

  return (
    <Panel
      title="AI Executive Brief"
      subtitle="Generated by Lumen · Lovable AI"
      right={
        <button
          onClick={run}
          disabled={loading}
          className="flex items-center gap-1.5 rounded-lg border border-border bg-surface px-3 py-1.5 text-xs text-muted-foreground transition hover:text-foreground disabled:opacity-50"
        >
          {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="h-3.5 w-3.5" />}
          Regenerate
        </button>
      }
    >
      {loading && !text && (
        <div className="space-y-3">
          <div className="skeleton h-4 w-3/4 rounded" />
          <div className="skeleton h-4 w-full rounded" />
          <div className="skeleton h-4 w-5/6 rounded" />
          <div className="skeleton h-4 w-2/3 rounded" />
        </div>
      )}
      {err && (
        <div className="rounded-lg border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">
          {err}
        </div>
      )}
      {text && (
        <div className="prose prose-sm prose-invert max-w-none prose-headings:font-display prose-headings:tracking-tight">
          <div className="mb-2 flex items-center gap-2 text-xs text-primary">
            <Sparkles className="h-3.5 w-3.5" /> AI-generated
          </div>
          <ReactMarkdown>{text}</ReactMarkdown>
        </div>
      )}
    </Panel>
  );
}
